name: Terraform Azure Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Validate JSON Secret (debugging)
      - name: Verify Secret Format
        run: |
          echo "Verifying JSON secret..."
          echo '${{ secrets.AZURE_CREDENTIALS }}' | jq empty || (echo "❌ Invalid JSON in secret!" && exit 1)
          echo "✅ Secret is valid JSON"

      # 3. Azure Login (bulletproof method)
      - name: Azure Login
        id: login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false

      # 4. Confirm login worked
      - name: Verify Azure Access
        if: steps.login.outputs.AZURE_LOGIN_RESULT != 'success'
        run: |
          echo "❌ Login failed! Check your credentials"
          exit 1

      # 5. Terraform Setup
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 6. Terraform Commands
      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
